# settings.yml 1.0.9.7
# this file: CC BY-ND 4.0
# zer0Kerbal
# created 01 Jan 2022
# updated 01 Oct 2022
# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

repository:
  # The name of the repository. Changing this will rename the repository
  name: FuelTanksPlus

  # A short description of the repository that will show up on GitHub
  # description: A set of fuel tanks that are longer than largest stock tanks in each diameter, plus fuel-filled nose cones for those diameters. These are meant to give you some visual choice of styles that are loosely inspired by real-world rockets from NASA, ESA, and private space firms (though that inspiration is mainly in color choice), while maintaining the style established in the Color Coded Canisters mod.
  # description: A set of fuel tanks that are 1.5x the length of the largest stock tanks in each diameter, plus fuel-filled nose cones for those diameters. These tanks are meant to give you some visual choice of styles that are loosely inspired by real-world rockets from NASA, ESA, and private space firms (though that inspiration is mainly in color choice), while maintaining the style established in the Color Coded Canisters mod (since CCC replaces stock visuals, any 'new' tanks should be spun off into a separate pack, and hence we have FTP) For Kerbal Space Program.

  # A URL with more information about the repository
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/207702-*/

  # A comma-separated list of topics to set on the repository
  topics: fuel,tanks,fueltanks,plus,necrobones,kerbal,kerbalspaceprogram,ksp,ksp-mods,ksp-parts,kerbal-space,kerbal-space-program,kerbal-mods,mods,zedk,contributions-welcome,hacktoberfest

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug 🐛
    color: CC0000
    description: An issue with the system. Something isn't working... KSC... we have an error code

  - name: "help wanted"
    color: 008672
    description: "assistance, help, input solicited"

  - name: duplicate
    color: FFFFF0
    description: "duplicated issue - it happens"

  - name: FAQ
    color: 78A1A5
    description: "Frequently Asked Question"

  - name: "semantic: adoption"
    # include the old name to rename an existing label
    oldname: adoption
    color: BADA55
    description: relating to adoption

  - name: "semantic: release"
    color: 00FF00
    description: release

  - name: "semantic: prerelease"
    color: 00FF00
    description: prerelase

  - name: "semantic: beta"
    color: 00FF00
    description: beta

  - name: "semantic: alpha"
    color: 00FF00
    description: alpha

  - name: "issue: text"
    color: FBCA04
    description: issue type

  - name: "issue: compatibility/patch"
    color: CC0DEB
    description: issue type

  - name: "issue: model"
    color: FBCA04
    description: issue type

  - name: "issue: texture"
    color: FBCA04
    description: issue type

  - name: "issue: sound"
    color: FBCA04
    description: issue type

  - name: "issue: config"
    color: FBCA04
    description: issue type

  - name: "issue: code"
    color: FBCA04
    description: issue type

  - name: "issue: documentation"
    color: FBCA04
    description: issue type

  - name: "issue: relationship"
    color: FBCA04
    description: issue type

  - name: "issue: license"
    color: FBCA04
    description: having to do with license/licensing

  - name: "issue: image"
    color: FBCA04
    description: deals with images and imgbot

  - name: "issue: install"
    color: FBCA04
    description: issue type

  - name: "issue: other"
    color: FBCA04
    description: issue type

  - name: "issue: external"
    color: FBCA04
    description: issue originates from external sources

  - name: "type: automation"
    color: fbca04
    description: issues for automation actions

  - name: "type: fix"
    color: 91ca55
    description: Iterations on existing features or infrastructure.

  - name: "type: infrastructure"
    color: ffdda8
    description: improvements or additions to project infrastructure

  - name: "type: localization"
    oldname: localization
    color: FFFFF0
    description: related to localization and translations

  - name: "type: testing"
    color: fbca04
    description: Related to testing.

  - name: "type: chore"
    color: fef2c0
    description: Converting measurements, reorganizing folder structure, and other necessary (but less impactful) tasks.

  - name: "type: discussion"
    oldname: discussion
    color: d4c5f9
    description: Questions, queries, posers, proposals and info that requires discussion.

  - name: "type: imgbot"
    color: d4c5f9
    description: imgbot automation.

  - name: "type: docs"
    color: fef2c0
    description: Related to documentation and information.

  - name: "type: pages"
    color: fef2c0
    description: Related to GitHub pages documentation and information.

  - name: "type: enhancement"
    oldname: "Mod-enhancement"
    # include the old name to rename an existing label
    color: 5ebeff
    description: Requested functionality, features, pages, workflows, endpoints, etc.

  - name: "type: feature"
    oldname: "Mod-feature"
    # include the old name to rename an existing label
    description: Brand new functionality, features, pages, workflows, endpoints, etc.

  - name: "type: request"
    oldname: "Mod-request"
    # include the old name to rename an existing label
    color: 5ebeff
    description: Requested functionality, features, pages, workflows, endpoints, etc.

  - name: "type: archive"
    color: FFFFF0
    description: archive

  - name: "type: upstream"
    oldname: "upstream"
    # include the old name to rename an existing label
    color: FFFFF0
    description: upstream or side stream

  - name: "type: pull request"
    oldname: "pull request"
    color: FFFFF0
    description: upstream or side stream

  - name: "work: choatic"
    color: FBCA04
    description: The situation is chaotic, novel practices used.

  - name: "work: complex"
    color: d4c5f9
    description: The situation is complex, emergent practices used.

  - name: "work: complicated"
    color: ffb8c6
    description: The situation is complicated, good practices used.

  - name: "work: obvious"
    color: 91ca55
    description: The situation is obvious, best practices used.

  - name: "state: approved"
    color: 91ca55
    description: Approved to proceed.

  - name: "state: blocked"
    color: d73a4a
    description: Something is blocking action.

  - name: "state: pending"
    color: fbca04
    description: Taking action, but need a few things to happen first. A feature that needs dependencies merged, or a bug that needs further data.

  - name: "state: inactive"
    color: e6e6e6
    description: No action needed or possible. The issue is either fixed, addressed better by other issues, or just out of product scope.

  - name: "state: planning"
    color: FFFF00
    description:

  - name: "state: won't fix"
    color: e6e6e6
    description: No action will be taken at this time

  - name: "hacktoberfest"
    color: ff9900
    description: flag for entry into hacktoberfest

  - name: "hacktoberfest-accepted"
    color: ff9900
    description: flag for stating PR is accepted as appropriate for hacktoberfest

  - name: "good-first-issue"
    color: AEF923
    description: flag for inclusion into good-first-issues listing

  - name: "contributions-welcome"
    color: AEF923
    description: flag for inclusion into contributions-welcome listing

  - name: "beginner-friendly"
    color: AEF923
    description: flag for inclusion into beginner-friendly listing

  - name: "invalid"
    color: FFFF00
    description: flagged as invalid

  - name: "spam"
    color: EB212E
    description: spam flag

# Milestones: define milestones for Issues and Pull Requests
#milestones:
#  - title: 2.0.3.0-adoption
#    description: progress toward 2.0.3.0-adoption
#    state: closed
#  - title: Previous Releases uploaded
#    description: progress toward Previous Releases uploaded
#    state: closed
#  - title: Localization - Master
#    description: progress toward total localization
#    state: closed
#  - title: Localization - English (United States) <en-us.cfg>
#    description: progress toward English (United States) <en-us.cfg> localization
#    state: open
#  - title: 2.0.2.0
#    description: progress toward archiving 2.0.2
#    state: closed
#  - title: 2.0.1.0
#    description: progress toward archiving 2.0.1
#    state: closed
#  - title: 2.0.0.0
#    description: progress toward archiving 2.0.0
#    state: closed
#  - title: 1.12.1.0
#    description: progress toward archiving 1.12.1
#    state: closed
#  - title: 1.12.0.0
#    description: progress toward archiving 1.12
#    state: closed
#  - title: 1.11
#    description: progress toward archiving 1.11
#    state: closed
#  - title: 1.10
#    description: progress toward archiving 1.10
#    state: closed
#  - title: 1.9.3
#    description: progress toward archiving 1.9.3
#    state: closed
#  - title: 1.9.2
#    description: progress toward archiving 1.9.2
#    state: closed
#  - title: 1.9.1
#    description: progress toward archiving 1.9.1
#    state: closed
#  - title: 1.9
#    description: progress toward archiving 1.9
#    state: closed
#  - title: 1.8.3
#    description: progress toward archiving 1.8.3
#    state: closed
#  - title: 1.8.2
#    description: progress toward archiving 1.8.2
#    state: closed
#  - title: 1.8.1
#    description: progress toward archiving 1.8.1
#    state: closed
#  - title: 1.8
#    description: progress toward archiving 1.8
#    state: closed
#  - title: 1.7
#    description: progress toward archiving 1.7
#    state: closed
#  - title: 1.6
#    description: progress toward archiving 1.6
#    state: closed
#  - title: 1.5
#    description: progress toward archiving 1.5
#    state: closed
#  - title: 1.4
#    description: progress toward archiving 1.4
#    state: closed
#  - title: 1.3.1
#    description: progress toward archiving 1.3.1
#    state: closed
#  - title: 1.3
#    description: progress toward archiving 1.3
#    state: closed
#  - title: 1.2.2
#    description: progress toward archiving 1.2.2
#    state: closed
#  - title: 1.2.1
#    description: progress toward archiving 1.2.1
#    state: closed
#  - title: 1.2
#    description: progress toward archiving 1.2
#    state: closed
#  - title: 1.1.1
#    description: progress toward archiving 1.1.1
#    state: closed
#  - title: 1.1
#    description: progress toward archiving 1.1
#    state: closed
#  - title: 1.0.5
#    description: progress toward archiving 1.0.5
#    state: closed
#  - title: 1.0.4
#    description: progress toward archiving 1.0.4
#    state: closed
#  - title: 1.0.3
#    description: progress toward archiving 1.0.3
#    state: closed
#  - title: 1.0.2
#    description: progress toward archiving 1.0.2
#    state: closed
#  - title: 1.0.1
#    description: progress toward archiving 1.0.1
#    state: closed
#  - title: 1.0
#    description: progress toward archiving 1.0
#    state: closed
#  - title: 0.11.2
#    description: progress toward archiving 0.11.2
#    state: closed
#  - title: 0.11.1
#    description: progress toward archiving 0.11.1
#    state: closed
#  - title: 0.11
#    description: progress toward archiving 0.11
#    state: closed
#  - title: 0.10.1
#    description: progress toward archiving 0.10.1
#    state: closed
#  - title: 0.10
#    description: progress toward archiving 0.10
#    state: closed
#  - title: 0.9.1
#    description: progress toward archiving 0.9.1
#    state: closed
#  - title: 0.9
#    description: progress toward archiving 0.9
#    state: closed
#  - title: 0.8.2
#    description: progress toward archiving 0.8.2
#    state: closed
#  - title: 0.8.1
#    description: progress toward archiving 0.8.1
#    state: closed
#  - title: 0.8
#    description: progress toward archiving 0.8
#    state: closed
#  - title: 0.7.1
#    description: progress toward archiving 0.7.1
#    state: closed
#  - title: 0.7
#    description: progress toward archiving 0.7
#    state: closed
#  - title: 0.6
#    description: progress toward archiving 0.6
#    state: closed
#  - title: 0.5
#    description: progress toward archiving 0.5
#    state: closed
#  - title: 0.4
#    description: progress toward archiving 0.4
#    state: closed
#  - title: 0.3
#    description: progress toward archiving 0.3
#    state: closed
#  - title: 0.2.1
#    description: progress toward archiving 0.2.1
#    state: closed
#  - title: 0.2
#    description: progress toward archiving 0.2
#    state: closed
#  - title: 0.1
#    description: progress toward archiving 0.1
#    state: closed
